#! /bin/sh

pass=`cat /passTMP`
echo password: $pass
useradd -mg users -p $pass -G wheel,storage,power -s /bin/zsh mar
chage -d 0 mar
echo mar:$pass | chpasswd
#chsh -s /bin/zsh mar
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers
echo befor configUser
#sudo -u mar ./configUser
echo after configUser
