#! /bin/bash

###partition drive
#
#

###Format drive partittions
#
timedatectl set-ntp true
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3


##Mount partitons
mount /dev/sda3 /mnt
mkdir /mnt/boot
mkdir /mnt/boot/efi
mount /dev/sda1 /mnt/boot/efi

##pacstrap
echo "Server = http://mirror.archlinux.no/$repo/os/$arch" | cat - /etc/pacman.d/mirrorlist > temp && mv temp /etc/pacman.d/mirrorlist
pacstrap /mnt base base-devel vim

##GenfsTab
genfstab -U /mnt >> /mnt/etc/fstab

##copy script part 2 into /mnt
cp part2 /mnt/part2

arch-chroot /mnt ./part2

