#! /bin/bash

set_timezone_info(){
    ln -sf /usr/share/zoneinfo/Europe/Oslo /etc/localtime
    hwclock --systohc
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
    locale-gen
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
}

set_hostname_info(){
    echo "127.0.0.1	localhost" > /etc/hosts
    echo "MyArch" > /etc/hostname
    echo "::1"      localhost >> /etc/hosts
    echo "127.0.1.1	MyArch.localdomain MyArch" >> /etc/hosts
}
install_bootloader_efi(){
    pacman --noconfirm -S grub efibootmgr dosfstools os-prober mtools 
}
install_personal_software(){
    pacman --noconfirm -S - < ./pkglist.txt
}


install_grub_efi(){
    ##install grub (efi)
    ##remember aspire boot reqires spesial folder in /boot
    grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck  
    grub-mkconfig -o /boot/grub/grub.cfg 
}

install_grub(){
    grub-install --target=i386-pc /dev/sda
    grub-mkconfig -o /boot/grub/grub.cfg 
}

##make new user
create_main_user(){
    useradd -mg users -p $1 -G wheel,storage,power -s /bin/bash mar
    chage -d 0 mar
    echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers
    sudo -u mar /configUser
}

cleanup(){
    rm /part2
    rm /pkglist.txt
    rm /passTMP
    rm /configUser
}

PASS=`cat /passTMP`
set_timezone_info
set_hostname_info
install_bootloader_efi
install_personal_software
systemctl enable NetworkManager
install_grub
create_main_user $PASS
echo "$PASS" | passwd mar --stdin 


