#! /bin/bash

set_timezone_info(){
    ln -sf /usr/share/zoneinfo/Europe/Oslo /etc/localtime
    hwclock --systohc
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
    locale-gen
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
}

set_hostname_info(){
    echo "127.0.0.1	localhost" > /etc/hosts
    echo "MyArch" > /etc/hostname
    echo "::1"      localhost >> /etc/hosts
    echo "127.0.1.1	MyArch.localdomain MyArch" >> /etc/hosts
}
install_personal_software(){
    pacman --noconfirm -S - < ./pkglist.txt
}

install_grub(){
    grub-install --target=i386-pc /dev/sda
    grub-mkconfig -o /boot/grub/grub.cfg
}

##make new user
create_main_user(){
    useradd -mg users -p $1 -G wheel,storage,power -s /bin/bash mar
    chage -d 0 mar
    echo mar:$1 | chpasswd
    chsh -s /bin/zsh mar
    echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers
    sudo -u mar /configUser
}


start_gnome_keyring_at_login(){
    sed -i '/auth       include      system-local-login/a auth       optional     pam_gnome_keyring.so' /etc/pam.d/login
    sed -i '/session    include      system-local-login/a session    optional     pam_gnome_keyring.so auto_start' /etc/pam.d/login
}

echo "chose password for system(root and mar user)"
read PASS

set_timezone_info
set_hostname_info
install_grub

install_personal_software
systemctl enable NetworkManager
git clone https://github.com/marnyg/AnsibleDesktopSetupManjaro.git /root/ansible
create_main_user $PASS
echo mar:$PASS | chpasswd
echo root:$PASS | chpasswd
pacman -S ansible --noconfirm
cd /root/ansible
ansible-galaxy install kewlfft.aur
#make ansible-local


#start_gnome_keyring_at_login
# cleanup
